Fix `TypeError: t is not a function`
Hyperapp requires a view function in [render](https://github.com/hyperapp/hyperapp/blob/1.1.2/src/index.js#L56) to exist