Jest update (#33)
* jsdom update prevents window.performance override

The new version of [jsdom](https://github.com/jsdom/jsdom) only has setter methods for certain `window` properties. Can be solved by setting method on property

* Fix `TypeError: t is not a function`

Hyperapp requires a view function in [render](https://github.com/hyperapp/hyperapp/blob/1.1.2/src/index.js#L56) to exist

* Update .gitignore